### ISSUE TITLE
Aula de 10/08

### ISSUE THREAD

**Issue by rvenson** [PriscilaPiuccohm/tcc#2]
Estudar e descrever sobre o clima organizacional nas escolas. Elaborar um documento contendo informações a respeito do que é um clima organizacional. Pesquisar literatura sobre o assunto. Escrever pelo menos uma página sobre clima organizacional nas escolas contendo referências (citações de outros autores) de livros ou artigos científicos.

Dica: Procurar esquemas (figuras) para representar o que é um clima organizacional.

**Comment by PriscilaPiuccohm** [comment]
beleza já to fazendo isso, peguei os tccs que eu tinha pesquisado e n tinha lido então vou usar tudo q tenho, e tenho que ver sobre o xe8 que a história é meia chatinha de achar, pois eu só achei mesmo do delphi e n mto do xe8, mas creio eu q eu acho alguma coisa como já achei os aplicativos rodados nele. Grata Priscila

**Comment by rvenson** [comment]
Ok.
